### ISSUE TITLE
Compilation in ARM GCC 8.2

### ISSUE THREAD

**Issue by elizabethshirley** [JarkkoPFC/fiber#1]
Just wanted to let you know that I needed to include cstdlib, and fix line 62-63 for the header to compile.
`#else FFUNC_INLINE inline`
`#define `

likely needs to be

`#else`
`#define FFUNC_INLINE inline`

**Comment by JarkkoPFC** [comment]
Ah yes, I actually submitted the fix for inline already. What's requiring the cstdlib? malloc/free?

Thanks, Jarkko

**Comment by elizabethshirley** [comment]
Yeah, Malloc/Free. I'm guessing that new isn't being included correctly.

**Comment by JarkkoPFC** [comment]
Thanks, this should be fixed now

**Comment by elizabethshirley** [comment]
Cool. I figured you would probably fix that quick, so I closed the ticket.

Very neat library btw, I'm hoping I have some time to try this in Keil and
System Workbench!
